### ISSUE TITLE
Crashes on ExUnit stopping

### ISSUE THREAD

**Issue by achedeuzot** [assert-value/assert_value_elixir#14]
Since upgrading to Elixir 1.15, I've got a random error with `AssertValue` and I'm not sure what I can do to fix it.

The error is:
```elixir
[error] GenServer AssertValue.Server terminating
** (stop) exited in: GenServer.call(#PID<0.4698.0>, :flush, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.15.6) lib/gen_server.ex:1074: GenServer.call/3
    (assert_value 0.10.1) lib/assert_value/server.ex:68: AssertValue.Server.handle_cast/2
    (stdlib 5.1) gen_server.erl:1103: :gen_server.try_handle_cast/3
    (stdlib 5.1) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:flush_ex_unit_io}}
```

It randomly arrives, more often on the CI and less locally so probably related to some timing / processing.

I'll try reproducing and pinpointing the issue for a better report but I wanted to post it here in case someone else is having the same issue.

**Comment by smetana** [comment]
Hi, thank you for the report. We employ certain timing tricks and I/O flush to synchronize the output during parallel testing. It appears that the changes in 1.15 are affecting them. We will investigate this issue.

**Comment by smetana** [comment]
Do you use any test results formatter other than the default ExUnit formatter? AssertValue only supports formatters that write to stdout. This might be the issue.

**Comment by achedeuzot** [comment]
I'm not using any custom formatter, other than the default one 🤔 I see there were changes in the elixir logger in elixir 1.15. I'm still investigating this and haven't pinpointed the issue.

**Comment by achedeuzot** [comment]
I guess it has something to do with the way ExUnit runs on erlang 26.1 and elixir 1.15.6.
Here are some additional error tracebacks, in case it helps:
```elixir
[error] GenServer AssertValue.Server terminating
** (stop) exited in: GenServer.call(#PID<0.1089.0>, :flush, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.15.6) lib/gen_server.ex:1074: GenServer.call/3
    (assert_value 0.10.1) lib/assert_value/server.ex:68: AssertValue.Server.handle_cast/2
    (stdlib 5.1) gen_server.erl:1103: :gen_server.try_handle_cast/3
    (stdlib 5.1) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:flush_ex_unit_io}}

[error] Process AssertValue.Server (#PID<0.620.0>) terminating
** (exit) exited in: GenServer.call(#PID<0.1089.0>, :flush, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.15.6) lib/gen_server.ex:1074: GenServer.call/3
    (assert_value 0.10.1) lib/assert_value/server.ex:68: AssertValue.Server.handle_cast/2
    (stdlib 5.1) gen_server.erl:1103: :gen_server.try_handle_cast/3
    (stdlib 5.1) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.1) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Initial Call: AssertValue.Server.init/1
Ancestors: [#PID<0.619.0>, #PID<0.618.0>]

[error] Child AssertValue.Server of Supervisor #PID<0.619.0> (Supervisor.Default) terminated
** (exit) exited in: GenServer.call(#PID<0.1089.0>, :flush, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
Pid: #PID<0.620.0>
Start Call: AssertValue.Server.start_link([])
```

I'll continue to see what I can find 🤔

**Comment by achedeuzot** [comment]
I noticed the crash is in one of the apps that doesn't use `assert_value`. 
I removed it from its `mix.exs` but the error persists 🤔

**Comment by achedeuzot** [comment]
I've continued to search but unfortunately, it's happening a bit randomly. I noticed that in some cases, when I run a fresh shell, the error doesn't trigger. When I run it multiple times, it often fails on the subsequent runs with the errors seen above. It looks like some sort of concurrency issue indeed.

**Comment by StandardMikeBenza** [comment]
I'm also encountering this, too.  My team has a similar setup: an umbrella app on 1.15.  We're on Erlang 25 though, not 26.

**Comment by StandardMikeBenza** [comment]
I did a bit of digging.  The StringIO is primarily closed in locations, which may be causing this ([1](https://github.com/elixir-lang/elixir/blob/5fa100b9972aca5dd0c807bcbe08f7ccf015a2fa/lib/ex_unit/lib/ex_unit/capture_server.ex#L197), [2](https://github.com/elixir-lang/elixir/blob/5fa100b9972aca5dd0c807bcbe08f7ccf015a2fa/lib/ex_unit/lib/ex_unit/capture_io.ex#L290)).  Both are related to capturing logs.  In our last 100 build failures, six were related to this crash.  Four of those six happened while testing an umbrella app that had been configured with `capture_log: true`.  I'm going to disable that to see if that fixes things.

**Comment by achedeuzot** [comment]
I remove the tests we have which use `capture_log: true` but the test run errors kept happening. For now, we've replaced all `assert_value()` back to `assert serialized_html(view) == "..."` and everything works 😢 😅 .

Nevertheless, it seems to be related to the output capturing indeed because after a failed run, the `.` shown by ExUnit for a successful test aren't displayed anymore and the shell seems to be a bit broken (raw mode ?).

**Comment by smetana** [comment]
I think I found the root of the issue. Please check latest master if it still crashes. 

Change assert_value dep in mix.exs to this:
```
defp deps do
  [
    {:assert_value,
    github: "assert-value/assert_value_elixir",
    ref: "3476fc18a4cd4c15c6d145648e438fdc44982aed"}
  ]
end
```

**Comment by StandardMikeBenza** [comment]
That didn't seem to help.  The CI build to use that change failed with the same error.

**Comment by smetana** [comment]
Does this help?
https://github.com/StandardMikeBenza/assert_value_elixir/pull/1/commits/dc7030298bd0f17e03127817c0da731a17f05776

**Comment by StandardMikeBenza** [comment]
It did work.  I _think_ it caused some extra log lines, and it _may_ cause some log line losses (though I'm assuming the process flushed its output before terminating), but it did seem to stop all our CI crashes related to assert_value.

**Comment by StandardMikeBenza** [comment]
> We have extensive integration tests for output and I can say that there are no extra or missing log lines produced by this change

I don't know enough (i.e. I don't know _anything_) about how ExUnit handles output to say that with confidence, so I didn't make a PR.  My concern is specifically around the case where the captured pid exits -- you presumably don't have tests for that because otherwise this would be a more tractable problem. 

That said, if you're confident that even when the captured pid exits that no log messages would be lost, I'm happy to make a PR.

**Comment by smetana** [comment]
Yep, we don't have tests for that. In the few cases where I encountered the error, it occurred after the ExUnit output test summary. Could you please provide me with some context around the error backtrace?

**Comment by StandardMikeBenza** [comment]
We have an umbrella app with a bunch of sub apps in it.  We run `mix test test/app1 test/app2 test/app3 test/app4 test/app5 test/app6` and it runs fine for a while.  Then we get:

```
[....]
Randomized with seed 950246
==> app3
Excluding tags: [:fail, :flappy]

..................
Finished in 7.0 seconds (7.0s async, 0.02s sync)
18 tests, 0 failures

Randomized with seed 950246
==> app4
18:48:32.376 domain=otp file=gen_server.erl line=949 mfa=:gen_server.error_info/7 pid=<0.567.0> registered_name=AssertValue.Server [error] GenServer AssertValue.Server terminating
** (stop) exited in: GenServer.call(#PID<0.4217.0>, :flush, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir 1.15.4) lib/gen_server.ex:1074: GenServer.call/3
    (assert_value 0.10.1) lib/assert_value/server.ex:68: AssertValue.Server.handle_cast/2
    (stdlib 3.17.2.2) gen_server.erl:695: :gen_server.try_dispatch/4
    (stdlib 3.17.2.2) gen_server.erl:771: :gen_server.handle_msg/6
    (stdlib 3.17.2.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:flush_ex_unit_io}}
```

And any subsequent test that uses `assert_value` will fail with:
```
1) test blah blah blah (Some.Module)
  apps/app5/test/some/module_test.exs:14
  ** (exit) exited in: GenServer.call(AssertValue.Server, {:reformat_expected?}, :infinity)
      ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
  code: assert_value(
  stacktrace:
    (elixir 1.15.4) lib/gen_server.ex:1063: GenServer.call/3
    test/some/module_test.exs:43: (test)
```

This applies to both 3476fc18a4cd4c15c6d145648e438fdc44982aed and [https://github.com/assert-value/assert_value_elixir/tree/v0.10.1](v0.10.1)

**Comment by smetana** [comment]
Unfortunately, this does not fix the problem. I encountered crash in the umbrella project after applying the fix.
```
==> app1
..
Finished in 0.02 seconds (0.00s async, 0.02s sync)
1 doctest, 1 test, 0 failures

Randomized with seed 474034
==> app2


  1) test greets the world (App2Test)
     apps/app2/test/app2_test.exs:7
     ** (exit) exited in: GenServer.call(AssertValue.Server, {:reformat_expected?}, :infinity)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
     code: assert_value App1.hello() == :world
     stacktrace:
       (elixir 1.15.7) lib/gen_server.ex:1063: GenServer.call/3
       test/app2_test.exs:8: (test)
```
In this case ExUnit is running but AssertValue is not. It appears that the problem lies in the start/stop synchronization mismatch between ExUnit and AssertValue apps.

**Comment by StandardMikeBenza** [comment]
I haven't seen the `* (exit) exited in: GenServer.call(AssertValue.Server, {:reformat_expected?}, :infinity)` with my changes, though I did see it with 3476fc18a4cd4c15c6d145648e438fdc44982aed.  In any case, I'll try cdbc72c today.

Isn't there still a short period between AssertValue shuts down and restarts in which that same error may occur?  I think it'll be a very very short period (probably shorter than ExUnit startup), but I just wanted to flag that there _might_ still be a problem for a short time.

**Comment by smetana** [comment]
I have even better solution: 3601067d1fba363f869fbb4d0215b1f8d2235e58
Why not skip IO flushing at the end of the suite? We won't interfere with the output after :suite_finished anyway and will avoid race condition at the end

**Comment by smetana** [comment]
I cleaned up the code, and we're going to release a new version based on the 11a8542f7c66b6984241025d138ce9a41947baf5
Unless we hear that this does not work for you. Please test.

**Comment by StandardMikeBenza** [comment]
I'll be able to test that starting on Monday.  We don't normally release on Fridays and we're a small team with most of our other reviewers are out today.

**Comment by StandardMikeBenza** [comment]
When you deleted 3601067d1fba363f869fbb4d0215b1f8d2235e58, it broke our CI, so I had to update to 11a8542.  I was able to push out a change so our next few CI builds will test it.  I'll be able to give you an update on Monday.

**Comment by achedeuzot** [comment]
Hello 👋 

I've retried with version [11e8542](https://github.com/assert-value/assert_value_elixir/commit/11a8542f7c66b6984241025d138ce9a41947baf5) and on the first run, I got the error above:
```elixir
** (exit) exited in: GenServer.call(AssertValue.Server, {:reformat_expected?}, :infinity)
         ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
```

I then cleaned the `_build` folder and re-ran tests multiple times and I couldn't manage to get it again. I also sent it to the CI and everything seems to be fine. It looks like this fix works 👍 ❤️

**Comment by smetana** [comment]
Great. Thank you for report and testing. We will release new package with the fix on Monday

Closed in https://github.com/assert-value/assert_value_elixir/commit/11a8542f7c66b6984241025d138ce9a41947baf5

**Comment by achedeuzot** [comment]
Thanks for the investigation and bugfix ❤️ 🧡 💛 💚 💙 💜
