### ISSUE TITLE
assert_value fails on assertions where String.Chars hasn't been implemented.

### ISSUE THREAD

**Issue by SkipMike** [assert-value/assert_value_elixir#2]
I was attempting some tests with `assert_value` this morning.

```
assert_value %{updated_fields: [:atom]}
```
blew up saying that String.Chars wasn't implemented. Without digging into the codebase yet, I'm thinking that this could be solved by using `inspect` instead of what's going on right now.

**Comment by smetana** [comment]
Hi. Thank you. There is a note in README which says "assert_value requires left argument to implement String.Chars protocol". Now I see that raising error in opposite case is confusing.
Using inspect for types without String.Chars would make sense.

**Comment by smetana** [comment]
Version 0.8.0 now supports all Elixir types (except not serializable like PID, Reference, etc...)
