### ISSUE TITLE
assert_value fails because it can't parse arguments

### ISSUE THREAD

**Issue by SkipMike** [assert-value/assert_value_elixir#3]
`mix format` will turn 

`assert_value FileParser.handle_demand(1, 2, 3)` into `assert_value(FileParser.handle_demand(1, 2, 3))`. I then get an error when accepting a new value 

`** (AssertValue.Parser.ParseError) Unable to parse assert_value arguments`

**Comment by SkipMike** [comment]
I was wrong about formatting being the problem. I'll try to point out what the problem is.

**Comment by smetana** [comment]
Hi. Thank you for reporting this.
Bugfix is already in master. We will release fixed version ASAP.

**Comment by smetana** [comment]
0.8.1 has been released
