### ISSUE TITLE
Use the code formatter instead of Macro.to_string to serialize values

### ISSUE THREAD

**Issue by tmbb** [assert-value/assert_value_elixir#5]
I'm testing some code that outputs some medium-size lists. They are currently inserted in the file as a single line in situations where the formatter would use more than one line, which is more readable.

The output should be something like:

```
assert_value fun(args) = [
  item1,
  item2
  item3,
  item4,
  item5
]
```

Instead of:

```
assert_value fun(args) = [item1, ..., item5]
```

**Comment by smetana** [comment]
It is already in our plans. But we need to drop support for Elixirs < 1.6 to do that

**Comment by tmbb** [comment]
Can't you detect the Elixir version and choose the formatter if available?

**Comment by smetana** [comment]
Sure. But then we will get different results in different Elixir versions. Something we trying to avoid. Formatter is still changing in every minor Elixir release. Of course, we will use it eventually. We just wait for it to stabilize a bit.

**Comment by tmbb** [comment]
Make it an explicit config option then. The output will still change with Elixir versions, but the user must opt in to that behavior. It looks like an acceptable compromise.

**Comment by smetana** [comment]
We'll take a look at it. Thank you

**Comment by smetana** [comment]
Please try use-elixir-formatter branch. How does it work for you?

**Comment by smetana** [comment]
New version 0.9.0 has been released. assert_value now uses Elixir Formatter to format values.
