### ISSUE TITLE
Large maps don't serialize correctly

### ISSUE THREAD

**Issue by SkipMike** [assert-value/assert_value_elixir#6]
I have some large nested maps that I'm using assert_value with and I'll get "..." just mixed into the noutput. I think this probably comes from using `inspect()` with out  specifying that the `limit` option.

I think the relevant options would be 
`[limit: :infinity, pretty: true, printable_limit: 1048576]`.

I think that should improve the look of the output while making it less likely that you stop printing what you want. An interesting idea is to even allow the user to increase the printable_limit when we call it or in config in case someone is doing something truly outside the norm.

**Comment by smetana** [comment]
Hello. This is because of a bug in Elixir's Macro.to_string https://github.com/elixir-lang/elixir/issues/7545
Please try use-elixir-formatter branch of assert_value_elixir and see how it will work for you.

**Comment by smetana** [comment]
Could you also please provide me with a test case? It may be not yet fixed in a new branch

**Comment by smetana** [comment]
Sorry. We fixed a different bug. The issue with big structures is still present.

**Comment by smetana** [comment]
The fix is not trivial and the issue will be resolved in next Elixir version. As a workaround, you may serialize actual value with `inspect` before passing it to assert_value as you proposed in the first comment
